version: "3.4"
services:
  vite_docker:
    image: node:20.11.1
    container_name: vite_docker
    env_file:
      - .env
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
