trigger:
  branches:
    include:
      - releases/*

name: v0.01$(Rev:.rr)

variables:
  - group: web-react-skeleton-azure

stages:
  - stage: Pull_request_build_stage
    displayName: "Pull Request Build Stage"
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: azure-pipeline/build_frontend.yml
        parameters:
          environment: "dev"

  - template: azure-pipeline/environments_loop.yml
